USE jungle_library_db;

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    Person_ID CHAR(4) NOT NULL,
    Book_ID CHAR(10) NOT NULL,
    Comment_Time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Rating INT,
    Content TEXT,
    PRIMARY KEY (Person_ID, Book_ID, Comment_Time),
    FOREIGN KEY (Person_ID) REFERENCES PERSON(Person_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Book_ID) REFERENCES BOOK(Book_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
