USE jungle_library_db;

DROP TABLE IF EXISTS AUTHOR_EMAIL;

CREATE TABLE AUTHOR_EMAIL (
    Author_ID CHAR(4) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PRIMARY KEY (Author_ID, Email),
    FOREIGN KEY (Author_ID) REFERENCES AUTHOR(Author_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
