USE jungle_library_db;

DROP TABLE IF EXISTS WRITES;

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR(10) PRIMARY KEY,
    Member_ID VARCHAR(10),
    Start_Date DATE NOT NULL,
    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
