USE jungle_library_db;

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    Employee_ID VARCHAR(10) PRIMARY KEY,
    Person_ID VARCHAR(10) NOT NULL,
    Member_ID VARCHAR(10),
    Start_Date DATE NOT NULL,

    FOREIGN KEY (Person_ID) REFERENCES PERSON(Person_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);
