USE jungle_library_db;

DROP TABLE IF EXISTS CATALOGING_MANAGER;

CREATE TABLE CATALOGING_MANAGER (
    Employee_ID VARCHAR(10) PRIMARY KEY,
    Trainer_ID INT,
    FOREIGN KEY (Employee_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Trainer_ID) REFERENCES TRAINER(Trainer_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


