USE jungle_library_db;

DROP TABLE IF EXISTS LIBRARY_SUPERVISOR;

CREATE TABLE LIBRARY_SUPERVISOR (
    Employee_ID VARCHAR(10) PRIMARY KEY,
    Trainer_ID INT,
    FOREIGN KEY (Employee_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Trainer_ID) REFERENCES TRAINER(Trainer_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);
