USE jungle_library_db;

DROP TABLE IF EXISTS BORROWING_RECORD;

CREATE TABLE BORROWING_RECORD (
    Record_ID INT AUTO_INCREMENT PRIMARY KEY,
    Payment_ID VARCHAR(10),
    Issue_Date DATE,
    Return_Due_Date DATE,
    FOREIGN KEY (Payment_ID) REFERENCES PAYMENT(Payment_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
