USE jungle_library_db;

DROP TABLE IF EXISTS BORROWS;

CREATE TABLE BORROWS (
    Record_ID INT,
    Member_ID VARCHAR(10),
    PRIMARY KEY (Record_ID, Member_ID),
    FOREIGN KEY (Record_ID) REFERENCES BORROWING_RECORD(Record_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);