USE jungle_library_db;

DROP TABLE IF EXISTS BORROWS;

CREATE TABLE BORROWS (
    Payment_ID VARCHAR(10),
    Member_ID VARCHAR(10),

    PRIMARY KEY (Payment_ID, Member_ID),

    FOREIGN KEY (Payment_ID) REFERENCES BORROWING_RECORD(Payment_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
