USE jungle_library_db;

DROP TABLE IF EXISTS CATALOGING_LOG;

CREATE TABLE CATALOGING_LOG (
    Manager_ID VARCHAR(10),
    Book_ID VARCHAR(10),
    Catalog_Date Date,
    PRIMARY KEY (Manager_ID, Book_ID),
    FOREIGN KEY (Manager_ID) REFERENCES CATALOGING_MANAGER(Employee_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Book_ID) REFERENCES BOOK(Book_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

