USE jungle_library_db;

DROP TABLE IF EXISTS MAINTAINS;

CREATE TABLE MAINTAINS (
    Receptionist_ID VARCHAR(10),
    Payment_ID VARCHAR(10),

    PRIMARY KEY (Receptionist_ID, Payment_ID),

    FOREIGN KEY (Receptionist_ID) REFERENCES RECEPTIONIST(Employee_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (Payment_ID) REFERENCES BORROWING_RECORD(Payment_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
