USE jungle_library_db;

DROP TABLE IF EXISTS ENTRY;

CREATE TABLE ENTRY (
  Payment_ID VARCHAR(10),
  Book_ID VARCHAR(10),
  PRIMARY KEY (Payment_ID, Book_ID),
  FOREIGN KEY (Payment_ID) REFERENCES BORROWING_RECORD(Payment_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Book_ID) REFERENCES BOOK(Book_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);