USE jungle_library_db;

DROP TABLE IF EXISTS INQUIRES;

CREATE TABLE INQUIRES (
    Inquiry_ID VARCHAR(10),
    Member_ID VARCHAR(10),
    Rating INT,   
    PRIMARY KEY (Inquiry_ID, Member_ID),
    
    FOREIGN KEY (Inquiry_ID) REFERENCES INQUIRY(Inquiry_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
